export const PRODUCT_MATERIAL_DESCRIPTIONS = {
  cotton: 'soft natural fiber with a subtle matte weave and gentle organic texture',
  polyester: 'smooth synthetic fabric with a slight sheen and consistent industrial finish',
  wool: 'thick natural fiber with characteristic fuzz, depth, and rich insulating texture',
  silk: 'luxurious natural fiber with high sheen, extreme smoothness, and fluid reflectivity',
  denim: 'rugged twill weave with distinctive diagonal texture and matte, durable appearance',
  leather: 'organic semi-matte surface with unique grain patterns and subtle natural highlights',
  wood: 'natural organic grain with characteristic warmth, matte finish, and tactile depth',
  metal: 'cold industrial surface with high specular highlights and sharp edge definition',
  glass: 'transparent or translucent surface with high reflectivity and clean sharp highlights',
  ceramic: 'smooth fired clay with characteristic weight and cool-to-touch surface',
  plastic: 'smooth synthetic surface with consistent color and controlled specular reflections',
  stone: 'rugged mineral surface with matte texture, natural variations, and heavy feel',
  concrete: 'industrial composite with porous matte texture and cool architectural tone',
} as const;

export const PRODUCT_FINISH_DESCRIPTIONS = {
  matte: 'non-reflective surface that absorbs light, creating soft gradients and no specular highlights',
  glossy: 'high-shine reflective surface with mirror-like specular highlights and sharp light transitions',
  satin: 'semi-matte finish with a soft, pearlescent glow and diffused highlights',
  brushed: 'directional metallic texture that creates elongated, soft specular streaks',
  polished: 'ultra-smooth mirror-like finish with high-contrast reflections and crisp highlights',
  textured: 'tactile surface with visible depth that creates micro-shadows and rich detail',
  distressed: 'aged surface with intentional wear, variations, and low-contrast reflectivity',
} as const;

export const HOME_ROOM_STYLE_PRESETS = {
  minimalist: {
    label: 'Minimalist',
    description: 'Clean, airy, and essentialist',
    designDescription: 'clean lines, zero clutter, emphasis on form and negative space',
    colorPalette: 'monochromatic whites, greys, and blacks with subtle warm undertones',
    keyMaterials: 'matte lacquer, brushed metal, light oak, smooth stone',
    stylingNotes: 'single focal point, no unnecessary accessories, perfectly aligned elements',
    companionProps: 'single architectural branch, one heavy coffee table book, minimal ceramic vase',
    surfaceType: 'honed marble or matte micro-cement',
    lightingSetup: 'soft diffused window light, high key, minimal shadows',
    colorGrade: 'desaturated, high clarity, clean whites',
    whiteBalance: '5600K (Daylight)',
    vignetteSurface: 'low-profile pedestal',
    vignetteProps: 'minimal geometric sculpture',
    vignetteMood: 'serene and focused',
  },
  scandinavian: {
    label: 'Scandinavian',
    description: 'Light, functional, and cozy hygge',
    designDescription: 'organic shapes, functional beauty, light wood tones',
    colorPalette: 'whites, soft greys, sage green, and muted blue',
    keyMaterials: 'light ash, blonde oak, textured wool, matte ceramic',
    stylingNotes: 'layered textures, natural elements, lived-in but tidy aesthetic',
    companionProps: 'linen throw, ceramic mug, small potted plant (Pilea)',
    surfaceType: 'blonde oak wood planks',
    lightingSetup: 'bright natural daylight, soft shadows, airy and bright',
    colorGrade: 'bright, natural, slightly lifted blacks',
    whiteBalance: '5200K (Clean Neutral)',
    vignetteSurface: 'wooden side table',
    vignetteProps: 'stacked neutral textiles',
    vignetteMood: 'warm and inviting',
  },
  'mid-century': {
    label: 'Mid-Century Modern',
    description: 'Retro-classic 1950s aesthetic',
    designDescription: 'tapered legs, geometric patterns, iconic furniture shapes',
    colorPalette: 'mustard yellow, teal, burnt orange, and walnut brown',
    keyMaterials: 'walnut wood, brass, velvet, molded plastic',
    stylingNotes: 'bold silhouettes, mix of organic and geometric forms',
    companionProps: 'brass accent lamp, abstract geometric art, colorful glass bowl',
    surfaceType: 'rich walnut veneer',
    lightingSetup: 'warm afternoon sun, graphic shadows, medium contrast',
    colorGrade: 'warm, vintage-inspired saturation, rich browns',
    whiteBalance: '4500K (Warm)',
    vignetteSurface: 'walnut credenza',
    vignetteProps: 'vintage analog camera or record player',
    vignetteMood: 'retro-sophisticated',
  },
  industrial: {
    label: 'Industrial',
    description: 'Raw, urban, and architectural',
    designDescription: 'exposed structures, salvaged materials, rugged utility',
    colorPalette: 'charcoal, rusted iron, brick red, and weathered wood',
    keyMaterials: 'blackened steel, reclaimed wood, exposed brick, leather',
    stylingNotes: 'unrefined edges, visible hardware, large scale elements',
    companionProps: 'Edison bulb lamp, metal gears, stack of weathered crates',
    surfaceType: 'weathered concrete or aged metal',
    lightingSetup: 'directional high contrast lighting, hard shadows, cinematic',
    colorGrade: 'gritty, high contrast, crushed blacks',
    whiteBalance: '4000K (Cool/Moody)',
    vignetteSurface: 'reclaimed wood workbench',
    vignetteProps: 'heavy iron tools or blueprint rolls',
    vignetteMood: 'raw and masculine',
  },
  bohemian: {
    label: 'Bohemian',
    description: 'Eclectic, colorful, and free-spirited',
    designDescription: 'global influences, maximalist textures, relaxed layers',
    colorPalette: 'terracotta, turquoise, deep ochre, and jewel tones',
    keyMaterials: 'rattan, macramé, colorful textiles, terracotta',
    stylingNotes: 'clashing patterns, plenty of greenery, casual arrangement',
    companionProps: 'woven wall hanging, multiple floor plants (Monstera), patterned kilim rug',
    surfaceType: 'unfinished wood or woven seagrass',
    lightingSetup: 'warm sunbeams, dappled light, glowing highlights',
    colorGrade: 'vibrant, warm, rich saturation',
    whiteBalance: '4800K (Warm Sunlight)',
    vignetteSurface: 'rattan stool',
    vignetteProps: 'incense burner or travel journals',
    vignetteMood: 'creative and relaxed',
  },
  japandi: {
    label: 'Japandi',
    description: 'Japanese zen meets Scandi function',
    designDescription: 'wabi-sabi philosophy, perfect imperfection, low-profile',
    colorPalette: 'oatmeal, charcoal, sand, and muted olive',
    keyMaterials: 'bamboo, dark oak, washi paper, rough-hewn stone',
    stylingNotes: 'intentional placement, balanced asymmetry, natural patina',
    companionProps: 'bonsai tree, ceramic tea set, simple calligraphy scroll',
    surfaceType: 'tatami mat or dark oak floor',
    lightingSetup: 'soft filtered light, long shadows, contemplative atmosphere',
    colorGrade: 'muted, organic tones, soft contrast',
    whiteBalance: '5000K (Soft Neutral)',
    vignetteSurface: 'low stone plinth',
    vignetteProps: 'single kintsugi bowl',
    vignetteMood: 'meditative and timeless',
  },
  coastal: {
    label: 'Coastal',
    description: 'Beachy, nautical, and relaxed',
    designDescription: 'airy feel, light-reflective surfaces, maritime accents',
    colorPalette: 'sky blue, crisp white, sand beige, and navy',
    keyMaterials: 'bleached wood, linen, wicker, sea glass',
    stylingNotes: 'light and breezy, nautical motifs, shells and driftwood',
    companionProps: 'driftwood piece, glass buoy, white linen cushion',
    surfaceType: 'distressed white-washed wood',
    lightingSetup: 'overblown coastal sun, bright and airy, minimal shadows',
    colorGrade: 'bright, cool highlights, airy exposure',
    whiteBalance: '6000K (Cool Daylight)',
    vignetteSurface: 'weathered driftwood table',
    vignetteProps: 'shell collection or nautical rope',
    vignetteMood: 'breezy and refreshing',
  },
  traditional: {
    label: 'Traditional',
    description: 'Classic, formal, and elegant',
    designDescription: 'symmetrical layouts, ornate details, rich heritage',
    colorPalette: 'burgundy, forest green, cream, and gold',
    keyMaterials: 'polished mahogany, silk, brass, crystal',
    stylingNotes: 'balanced composition, classic proportions, refined detail',
    companionProps: 'crystal decanter, gilt-framed art, porcelain vase',
    surfaceType: 'polished parquet or oriental rug',
    lightingSetup: 'warm ambient glow, soft key light, classic shadows',
    colorGrade: 'rich, timeless, elegant depth',
    whiteBalance: '3200K (Warm Tungsten-style)',
    vignetteSurface: 'polished mahogany side table',
    vignetteProps: 'antique brass clock or leather-bound books',
    vignetteMood: 'stately and refined',
  },
} as const;

export const HARDLINES_CONTEXT_PRESETS = {
  desk_workspace: {
    label: 'Modern Workspace',
    description: 'Professional desk setup',
    environmentDescription: 'clean modern desk, large monitor softly visible in background, minimal tech accessories',
    placementSurface: 'matte grey desktop or light oak wood',
    companionObjects: 'mechanical keyboard, designer notebook, designer pen',
    impliedActivity: 'creative professional work',
    timeOfDay: 'mid-morning productivity light',
    lensRecommendation: '50mm prime',
    lightingSetup: 'cool LED key light from side, soft fill, modern tech vibe',
    colorGrade: 'clean tech blue tones, high clarity',
    whiteBalance: '5500K',
  },
  kitchen_counter: {
    label: 'Kitchen Counter',
    description: 'Modern culinary environment',
    environmentDescription: 'sleek kitchen counter, subway tile backsplash, modern appliance in background',
    placementSurface: 'white marble or dark quartz countertop',
    companionObjects: 'fresh herbs, designer cutting board, kitchen towel',
    impliedActivity: 'modern home cooking and prep',
    timeOfDay: 'bright morning light',
    lensRecommendation: '35mm wide-standard',
    lightingSetup: 'bright overhead diffused light, specular highlights on tiles',
    colorGrade: 'clean, warm neutral, food-safe aesthetic',
    whiteBalance: '5000K',
  },
  outdoor_adventure: {
    label: 'Outdoor Adventure',
    description: 'Rugged nature setting',
    environmentDescription: 'rugged terrain, granite rocks, out-of-focus pine forest background',
    placementSurface: 'flat natural stone or weathered log',
    companionObjects: 'adventure map, climbing carabiner, water bottle',
    impliedActivity: 'hiking, exploration, and durability testing',
    timeOfDay: 'harsh midday sun for high contrast',
    lensRecommendation: '85mm for edge separation',
    lightingSetup: 'bright natural sun, high contrast, hard shadows',
    colorGrade: 'rugged, high contrast, earthy greens and browns',
    whiteBalance: '5600K',
  },
  gym_fitness: {
    label: 'Gym / Fitness',
    description: 'Performance training environment',
    environmentDescription: 'modern boutique gym, rubber flooring, industrial gym equipment in background',
    placementSurface: 'textured gym mat or weight bench',
    companionObjects: 'shaker bottle, gym towel, heart rate monitor',
    impliedActivity: 'high-intensity performance training',
    timeOfDay: 'cool gym interior lighting',
    lensRecommendation: '50mm standard',
    lightingSetup: 'dramatic top-down shadows, high sweat-like speculars',
    colorGrade: 'cool, high contrast, dynamic shadow detail',
    whiteBalance: '6500K',
  },
  commute: {
    label: 'Daily Commute',
    description: 'Urban transit and city life',
    environmentDescription: 'modern train interior or city bus window, urban blur outside',
    placementSurface: 'metallic transit seat or composite tray table',
    companionObjects: 'transit pass, earbuds case, modern backpack',
    impliedActivity: 'urban commuting and on-the-go lifestyle',
    timeOfDay: 'overcast city light',
    lensRecommendation: '35mm for environmental context',
    lightingSetup: 'diffused natural light from window, low contrast',
    colorGrade: 'urban grey tones, slightly cinematic',
    whiteBalance: '5800K',
  },
  bedside_table: {
    label: 'Bedside Table',
    description: 'Intimate nighttime environment',
    environmentDescription: 'cozy bedroom, soft bedding in background, warm lamp glow',
    placementSurface: 'wooden bedside table with soft texture',
    companionObjects: 'ceramic mug, sleep mask, thick novel',
    impliedActivity: 'relaxing before sleep',
    timeOfDay: 'late evening, warm ambient glow',
    lensRecommendation: '85mm macro',
    lightingSetup: 'warm single source lamp light, deep soft shadows',
    colorGrade: 'extremely warm, low contrast, cozy ambiance',
    whiteBalance: '2800K',
  },
  living_room_shelf: {
    label: 'Modern Shelf',
    description: 'Curated home display',
    environmentDescription: 'minimalist living room, designer shelf, neutral wall background',
    placementSurface: 'clean white shelf or dark walnut tray',
    companionObjects: 'art book, small sculpture, trailing plant',
    impliedActivity: 'interior decoration and curation',
    timeOfDay: 'soft afternoon window light',
    lensRecommendation: '50mm prime',
    lightingSetup: 'soft side-lit window light, long gentle shadows',
    colorGrade: 'balanced, high dynamic range, soft tones',
    whiteBalance: '5200K',
  },
} as const;

export const SKIN_TONE_DESCRIPTIONS = {
  fair: 'very fair skin tone, light complexion',
  light: 'light skin tone, slightly warm undertones',
  medium: 'medium skin tone, balanced warm undertones',
  tan: 'tan skin tone, warm golden-brown complexion',
  deep: 'deep rich skin tone, warm dark complexion',
} as const;

export const MODEL_POSE_PRESETS = {
  standing_straight: 'standing straight, feet shoulder-width apart, neutral natural posture, arms relaxed at sides',
  relaxed: 'relaxed casual stance, slight weight shift to one side, natural and approachable',
  hands_on_hips: 'hands resting on hips, confident posture, shoulders back, slightly forward-facing',
  walking: 'mid-stride walking pose, natural movement, one foot forward, arms in natural swing',
  editorial: 'strong editorial pose, angular and deliberate, fashion-forward body positioning',
} as const;

export const LIFESTYLE_SCENE_PRESETS = {
  urban_street: {
    label: 'Urban Street',
    description: 'City environment, authentic street style',
    sceneDescription: 'busy urban street with soft-focus city background, brick walls, natural street textures, authentic urban environment',
    timeOfDay: 'golden hour afternoon',
    lightingMood: 'warm natural sunlight from the side, soft fill shadows, natural urban ambient light',
    sceneActivity: 'casual walking or standing naturally',
    lensType: '35mm street photography lens equivalent',
    shotType: 'three-quarter body shot',
    dof: 'medium depth of field, background slightly soft',
    colorGrade: 'warm, slightly cinematic, natural street photography tones',
  },
  minimal_indoor: {
    label: 'Clean Interior',
    description: 'Scandinavian minimal, natural light',
    sceneDescription: 'clean Scandinavian interior, white walls, light oak floor, minimal furniture softly visible in background',
    timeOfDay: 'midday natural window light',
    lightingMood: 'soft diffused natural light from left window, minimal controlled shadows, airy feel',
    sceneActivity: 'standing naturally, relaxed posture',
    lensType: '50mm standard lens equivalent',
    shotType: 'full body shot',
    dof: 'medium-shallow depth of field, background subtly blurred',
    colorGrade: 'clean, neutral, slightly airy and fresh',
  },
  outdoor_nature: {
    label: 'Outdoor Nature',
    description: 'Green outdoor setting, golden light',
    sceneDescription: 'lush outdoor setting, green foliage background, natural environment, park or garden, natural textures',
    timeOfDay: 'morning golden hour',
    lightingMood: 'soft dappled natural light filtering through trees, warm and inviting',
    sceneActivity: 'casual outdoor movement or standing',
    lensType: '85mm portrait lens equivalent',
    shotType: 'three-quarter body shot',
    dof: 'shallow depth of field, background softly and beautifully blurred (bokeh)',
    colorGrade: 'fresh, natural, slightly warm, earthy tones',
  },
  studio_editorial: {
    label: 'Studio Editorial',
    description: 'High-fashion studio, dramatic lighting',
    sceneDescription: 'high-fashion editorial studio, seamless backdrop, controlled professional environment',
    timeOfDay: 'controlled studio lighting',
    lightingMood: 'dramatic split lighting, one hard key light at 45°, deep controlled shadows, high contrast',
    sceneActivity: 'editorial fashion pose',
    lensType: '85mm portrait lens equivalent',
    shotType: 'three-quarter body shot',
    dof: 'sharp focus throughout entire frame',
    colorGrade: 'high contrast, editorial, punchy, magazine-quality',
  },
} as const;

export const CAMPAIGN_PRESETS = {
  minimalist_luxury: {
    label: 'Quiet Luxury',
    description: 'Clean, premium, Apple/Bottega aesthetic',
    poseDescription: 'minimal, confident, slightly asymmetric stance, understated elegance',
    photographyDescription: 'Camera: 85mm. Lighting: single large octabox, feathered soft light, long gentle shadows. Background: pure matte white or very light warm grey. Dominant negative space composition. The garment breathes.',
    moodDescription: 'quiet luxury, confident, premium, effortless',
  },
  street_energy: {
    label: 'Street Energy',
    description: 'Urban, dynamic, streetwear aesthetic',
    poseDescription: 'dynamic movement, energy, slight motion blur on extremities, authentic street attitude',
    photographyDescription: 'Camera: 35mm wide angle. Lighting: natural urban overcast light, flat and even. Background: urban environment, architecture or walls soft-focus. Gritty and real.',
    moodDescription: 'energetic, authentic, youthful, bold, street credibility',
  },
  neon_tech: {
    label: 'Neon Tech',
    description: 'Futuristic, neon-lit, editorial',
    poseDescription: 'strong angular editorial pose, commanding presence, facing camera or three-quarter turn',
    photographyDescription: 'Camera: 50mm. Lighting: dramatic neon rim lighting in purple/blue/pink tones, dark near-black background with selective dramatic illumination on subject. High contrast chiaroscuro.',
    moodDescription: 'futuristic, bold, high-fashion editorial, digital age luxury',
  },
  organic_natural: {
    label: 'Organic Natural',
    description: 'Warm, sustainable, earth-toned',
    poseDescription: 'relaxed, natural, authentic human movement, genuine expression',
    photographyDescription: 'Camera: 85mm. Lighting: golden hour natural sunlight, warm and enveloping. Setting: natural outdoor environment, earth tones surrounding, organic textures.',
    moodDescription: 'natural, warm, authentic, sustainable brand energy, human connection',
  },
} as const;
